### ISSUE TITLE
Getting permission denied 

### ISSUE THREAD

**Issue by bhatiaravi18** [keithf4/pg_bloat_check#25]
Hi Keith,

I am getting below error : 

-bash-4.2$ PGPASSWORD=**** ./pg_bloat_check.py -c "host=xxxx dbname=abc user=postgres"  -z 10485760 -p 45 -s
 5242880
Traceback (most recent call last):
  File "./pg_bloat_check.py", line 698, in <module>
    get_bloat(conn, tuple(exclude_schema_list), tuple(include_schema_list), exclude_object_list)
  File "./pg_bloat_check.py", line 330, in get_bloat
    cur.execute(sql)
  File "/usr/lib64/python2.7/site-packages/psycopg2/extras.py", line 120, in execute
    return super(DictCursor, self).execute(query, vars)
psycopg2.ProgrammingError: permission denied for schema pg_toast

Note the postgresql is running on the google cloudsql GCP

Regards:
Ravi

**Comment by keithf4** [comment]
I see you're running as the postgres user, so assuming that is a superuser? Not sure if GCP puts any restrictions on what its superusers are allowed to see. Generally the pg_toast schema is not that restrictive that I'm aware.

**Comment by keithf4** [comment]
Closing this issue for now. Please feel free to reopen if you are still having issues.

**Comment by keithf4** [comment]
The pg_toast schema is critical to being able to accurately assess the bloat of any table that uses the TOAST system. Otherwise you can miss extremely large amounts of space being used since the pgstattuple extension does not account for it when scanning the base table.

I would contact Azure support about this. Blocking simple read access to the pg_toast schema seems to be going a bit overboard if that's what they're doing.

**Comment by keithf4** [comment]
What version of PostgreSQL are you running? If you're on at least version 14 you could try granting the role that is running the bloat check the `pg_read_all_data` role. It will need that at a minimum anyway in order to scan all possible tables. Not sure if they've restricted that built in role's ability to see pg_toast.
